### ISSUE TITLE
Training on data only from current round ?

### ISSUE THREAD

**Issue by pp30** [congyingxia/IncrementalFSTC#1]
Hi !
Firstly thanks for sharing the code for the paper. I am trying to implement the paper for the "No_base_Intent" setting. In paper, Section 3 Problem Formulation - Requirements, it is mentioned that "(i) For the training of ith round , the system can only access the newly added few-shot examples and label names **in this round**. The system is **not allowed** to re-train on the (full or partial) examples of preceding classes."
 
However, the code output of subsequent rounds n2,n3.... suggest that at every round, the model is being _trained on data from previous rounds also_. This seems to not satisfy the main training requirement stated in paper. Kindly clarify on this issue. I have attached the screenshot of model output at round n3 for your reference.   

<img width="754" alt="round n3 op screenshot" src="https://user-images.githubusercontent.com/50921756/119852276-c6d13e00-bf2c-11eb-8664-f9c34a9238f3.png">

**Comment by congyingxia** [comment]
Hi, thanks for your interest! Yes, the system is not allowed to re-train on previous examples. However, the model is trained based on previous rounds. It's an incremental training process. The model of round3 is trained on the model from round2. And the model of round2 is trained based on the model from round1. Here, we just train the model on n1 to get the model from round1. Then we use n2 and model from round1 to get the model from round2. And we use it as a start point for round3. In round3, we only use the examples in n3.
