### ISSUE TITLE
MNLI_pretrained.pt

### ISSUE THREAD

**Issue by pp30** [congyingxia/IncrementalFSTC#2]
Hi,
Can u share the MNLI_pretrained.pt file for starting the incremental training upon Roberta pre-trained on MNLI entailment dataset? Currently, I am running without loading pre-trained weights and observing reduced performance

**Comment by congyingxia** [comment]
Hi, I've added the link for the pre-trained weights in Readme. Please checkout the new version.

**Comment by pp30** [comment]
Thanks for sharing !
